### PR TITLE
[Bugfix] Fix logging calls that drop their message at runtime, and guard against regressions

### LINKED ISSUE #4539: [Bug] Logging calls pass more args than their format string consumes, so the message is dropped at runtime
### Describe the bug

Three `logger.*` calls in `lmcache/` pass more positional arguments than their format string consumes.

`logging` renders a record lazily as `msg % args`, so these calls raise `TypeError: not all arguments converted during string formatting` *inside* the logging machinery. Python's logging catches that and prints `--- Logging error ---` plus a traceback to stderr — **the intended message is never emitted**.

All three sit on failure paths, which is exactly where losing the message hurts most.

**1. `lmcache/v1/storage_backend/p2p_backend.py:155`** — two arguments, one placeholder. The caught exception `e` is silently dropped:

```python
except Exception as e:
    logger.error("Failed to close peer %s lookup socket", self.peer_init_url, e)
```

**2. `lmcache/v1/storage_backend/connector/mock_connector.py:266`** and **3. `mock_connector.py:278`** — a stray comma where implicit string concatenation was intended, so the message is truncated and its tail silently becomes an argument:

```python
logger.warning(
    f"Mock object is None on {i}",
    f" out of {len(mock_objs)} objects",
)
```

```python
logger.warning(
    "Failed to allocate memory even with",
    f" busy loop on {i} out of {len(mock_objs)} objects",
)
```

### To Reproduce

```python
import logging, sys

logging.basicConfig(level=logging.DEBUG, stream=sys.stdout)
log = logging.getLogger("repro")
log.error("Failed to close peer %s lookup socket", "tcp://1.2.3.4:80", ValueError("boom"))
```

Output — note the message and the exception are both lost:

```
--- Logging error ---
Traceback (most recent call last):
  ...
  File ".../logging/__init__.py", line 400, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Message: 'Failed to close peer %s lookup socket'
Arguments: ('tcp://1.2.3.4:80', ValueError('boom'))
```

### Why CI does not catch this today

Ruff's `PLE1205` / `PLE1206` (logging too-many / too-few args) are not in the `select` list in `pyproject.toml`, and `G` (flake8-logging-format) is commented out.

Enabling **only** `PLE1205` and `PLE1206` reports exactly the two static cases above and nothing else repo-wide, so the rules can be turned on with no additional cleanup:

```
$ ruff check --select PLE1205,PLE1206 .
lmcache/v1/storage_backend/connector/mock_connector.py:278:17: PLE1205 Too many arguments for `logging` format string
lmcache/v1/storage_backend/p2p_backend.py:155:13: PLE1205 Too many arguments for `logging` format string
Found 2 errors.
```

(For contrast, the full `G` ruleset currently reports 511 findings, mostly the f-string logging that is already being migrated incrementally — so `G` is deliberately out of scope here.)

Ruff cannot see through the f-string in case 2, so that variant needs a small test to stay covered while the f-string → `%`-format migration is in progress.

### Environment

- LMCache `dev` @ `0373a573`
- Bugs introduced in #1500 (Sep 2025) and #2148 (Dec 2025); both still present on `dev`.

I have a fix ready and will open a PR referencing this issue.

### PR DESCRIPTION
**Pull request by alooshxl**
**What this PR does / why we need it**:

Fixes #4539

Three `logger.*` calls passed more positional arguments than their format string consumes. `logging` renders a record lazily as `msg % args`, so each of these raises `TypeError: not all arguments converted during string formatting` *inside* the logging machinery. Python's logging swallows that and prints a `--- Logging error ---` traceback to stderr instead — **the intended message is never emitted**. All three sit on failure paths, which is exactly where losing the message hurts most.

**1. `p2p_backend.py`** — two arguments, one placeholder. The caught exception had no placeholder to receive it, so the reason a peer socket failed to close was discarded entirely:

```python
 except Exception as e:
-    logger.error("Failed to close peer %s lookup socket", self.peer_init_url, e)
+    logger.error(
+        "Failed to close peer %s lookup socket: %s", self.peer_init_url, e
+    )
```

**2 & 3. `mock_connector.py`** — a stray comma where implicit string concatenation was intended. This both truncated the message ("Failed to allocate memory even with") and turned its tail into an argument. Rewritten as `%`-format, matching the convention in #3372:

```python
 logger.warning(
-    "Failed to allocate memory even with",
-    f" busy loop on {i} out of {len(mock_objs)} objects",
+    "Failed to allocate memory even with busy loop on %d out of "
+    "%d objects",
+    i,
+    len(mock_objs),
 )
```

**Preventing regressions.** `PLE1205`/`PLE1206` were not in the ruff `select` list, so nothing in CI catches this. Enabling just those two rules reports **exactly the two static cases fixed here and nothing else repo-wide**, so they turn on with no extra cleanup:

```
$ ruff check --select PLE1205,PLE1206 .
All checks passed!     # after this PR; 2 errors before it
```

I deliberately left `G` (flake8-logging-format) commented out — it currently reports 511 findings, mostly the f-string logging already being migrated file-by-file.

Ruff cannot see through an f-string, so case 2 above stays invisible to `PLE1205`. `tests/test_logging_format.py` closes that gap with a small AST walk over `lmcache/`. It is stdlib-only, runs in <1s, and reports every offending call in one assertion:

```
AssertionError: Logging calls would raise TypeError at runtime:
  lmcache/v1/storage_backend/connector/mock_connector.py:266 expects 0 arg(s) but 1 were supplied: 'Mock object is None on '
  lmcache/v1/storage_backend/connector/mock_connector.py:278 expects 0 arg(s) but 1 were supplied: 'Failed to allocate memory even with'
  lmcache/v1/storage_backend/p2p_backend.py:155 expects 1 arg(s) but 2 were supplied: 'Failed to close peer %s lookup socket'
```

**Special notes for your reviewers**:

- Verified the test actually catches the bugs: it fails with all three findings above when the two source fixes are reverted, and passes with them applied.
- The checker is intentionally conservative to avoid false positives on unrelated code — it skips `*args` splats, `%(name)s` mapping style, and `*` width/precision, and only treats a receiver whose name contains "log" as a logger.
- Ran locally on `dev` @ `0373a573`: `ruff check` (clean repo-wide with the new rules), `ruff format --check` (1177 files already formatted), `isort`, `codespell`, the SPDX header hook, and `mypy` on the new file — all clean.
- Happy to split the `pyproject.toml` rule change into its own PR if you would rather keep the fix and the lint change separate.

**If applicable**:

- [ ] this PR contains user facing changes - docs added
- [x] this PR contains unit tests

### CODE REVIEW

File: pyproject.toml [hunk 1]
```diff
@@ -87,6 +87,10 @@ select = [
     # "I",
     # flake8-logging-format
     #"G",
+    # pylint: logging call passes too many / too few args for its format string.
+    # Such a call raises TypeError inside logging and the message is dropped.
+    "PLE1205",
```
Comment (zhengfeihe) [inline pyproject.toml:92]: This is kinda too specific, why not just 

"PLE"

File: tests/test_logging_format.py [hunk 2]
```diff
@@ -0,0 +1,145 @@
+# SPDX-License-Identifier: Apache-2.0
```
Comment (zhengfeihe) [inline tests/test_logging_format.py:1]: Thanks for writing the tests! But I don't think we need a extra tests for this. It's kinda over-testing from my perspective, can you remove it ? CI is already pretty heavy now I think

**Review by zhengfeihe — COMMENTED** [review]
Thanks for the fix~ Please check comments.
