### PR TITLE
[Bugfix] Fix CacheBlend compatibility with vLLM V1 Engine (v0.17.1)

### PR DESCRIPTION
**Pull request by chjs**
**What this PR does / why we need it**:

Fix multiple compatibility issues preventing CacheBlend (`blend_kv_v1` example) from working with vLLM v0.17.1 (V1 Engine Alpha).

Refs #2306 — Documents the required vLLM-side patch for `register_model`
Refs #2355 — Provides vLLM v0.17.1 + LMCache compatibility for CacheBlend
Refs #2921 — Updates `blend_kv_v1` README with v0.17.1 reproduction steps
Refs #2262 — Adds dynamic `rope_scaling` retrieval via `getattr`

### Root Cause

vLLM V1 Engine (v0.17.1) introduced several breaking changes that affect CacheBlend:

- `vllm.attention` module relocated to `vllm.model_executor.layers.attention`
- `get_input_embeddings()` replaced with `model.embed_input_ids()`
- Token IDs wrapped in immutable `ConstantList` instead of plain `list`
- `MistralForCausalLM` not registered as a supported model for blending

### Issues Fixed

| # | File | Issue | Fix |
|---|------|-------|-----|
| 1 | `compute/attention/flash_attn.py`, `flash_infer_sparse.py` | `ModuleNotFoundError: No module named 'vllm.attention'` | Update import path to `vllm.model_executor.layers.attention` |
| 2 | `compute/attention/utils.py` | `ImportError` from flashinfer version mismatch at module load time | Lazy import `LMCFlashInferSparseBackend` only when `enable_sparse=True` |
| 3 | `integration/vllm/vllm_v1_adapter.py` | `TypeError: Encoding objects of type ConstantList is unsupported` | Convert `request.all_token_ids` to `list()` before msgpack serialization |
| 4 | `compute/models/base.py` | `AttributeError: 'MistralForCausalLM' object has no attribute 'get_input_embeddings'` | Use `vllm_model.model.embed_input_ids()` (V1 API) |
| 5 | `compute/models/base.py` | `rope_scaling` hardcoded to `None` | Use `getattr(rotary_emb, 'rope_scaling', None)` for forward compatibility |
| 6 | `compute/models/utils.py` | `NotImplementedError: Model type MistralForCausalLM is not supported in LMCache` | Add `MistralForCausalLM` to supported models (reuses `LMCLlamaModel`) |
| 7 | `examples/blend_kv_v1/README.md` | Outdated vLLM ad-hoc patch instructions | Update for v0.17.1 `initialize_from_config()` patch location |

### Testing

- **Environment**: vLLM v0.17.1, LMCache latest dev, Python 3.12, A100 GPU
- **Model**: `mistralai/Mistral-7B-Instruct-v0.2`
- **CPU backend**: `python blend.py` — 4 requests (warmup, first/store, second/blend, third/blend) all passed
- **Disk backend**: `python blend.py --use-disk` — passed
- **Cache hit**: 6,523 tokens reused via CacheBlend on second/third requests (~62% hit rate)
- **Speedup**: first request 0.80s → third request 0.47s (41% faster with blend)

Key log excerpts

```
Registering vllm model for vllm-instance
Creating blender for vllm-instance
Max K error (fused): 0.0078125
LMCache initialized for role KVConnectorRole.WORKER with version 0.4.3.dev73

Reqid: 0-..., Total tokens 2499, LMCache hit tokens: 0           (warmup)
[req_id=0-...] Stored 2304 out of total 2304 tokens               (warmup store)
Generation took 0.23 seconds, warmup request done.

Reqid: 1-..., Total tokens 10536, LMCache hit tokens: 0           (first)
[req_id=1-...] Stored 8186 out of total 8192 tokens                (first store)
Generation took 0.80 seconds, first request done.

Reqid: 2-..., Total tokens 10537, LMCache hit tokens: 6523        (second — blend)
Retrieved 6519 out of 6523 out of total 6523 tokens                (retrieve + blend)
[req_id=2-...] Stored 3971 out of total 10496 tokens               (new tokens stored)
Generation took 0.52 seconds, second request done.

Reqid: 3-..., Total tokens 10538, LMCache hit tokens: 6523        (third — blend)
Retrieved 6519 out of 6523 out of total 6523 tokens
Generation took 0.47 seconds, third request done.
```

**Special notes for your reviewers**:

- No changes to core CacheBlend algorithm or storage backends
- All changes are vLLM V1 API compatibility fixes
- `MistralForCausalLM` reuses `LMCLlamaModel` — Mistral shares an identical attention architecture (GQA + RoPE) with Llama and Qwen2
- A corresponding vLLM-side patch (`VLLMModelTracker.register_model()` in `gpu_worker.py`) is required and documented in the updated README, but is not included in this PR as it targets the vLLM repository
- The `Pin count of MemoryObj is negative` warnings observed during testing are a pre-existing issue in the latest dev branch, unrelated to this PR

**If applicable**:

- [x] this PR contains user facing changes - docs added
- [ ] this PR contains unit tests

---

> [!NOTE]
> **Medium Risk**
> Updates several vLLM integration points (request token handling, attention backend imports, and model embedding access), which are runtime-critical and could break inference if version assumptions are wrong. Changes are narrowly scoped to vLLM V1 compatibility and reduce startup failures via lazy imports.
> 
> **Overview**
> Restores CacheBlend support on vLLM V1 (tested with v0.17.1) by updating LMCache’s vLLM integration to match breaking API moves and data types.
> 
> Fixes include converting `request.all_token_ids` to a plain `list` before cache lookup/serialization, switching attention-layer imports to `vllm.model_executor.layers.attention`, and updating embedding access to `model.embed_input_ids()` for V1 engines. It also lazy-loads the FlashInfer sparse backend to avoid engine init failures when optional deps don’t match, expands blending model support to include `MistralForCausalLM`, and updates the `blend_kv_v1` README with the required vLLM-side model registration patch.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 9f8aa4d6ee70a2a05657470f3b84d3298c05d8a1. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: examples/blend_kv_v1/README.md [hunk 1]
```diff
@@ -1,19 +1,37 @@
...
+
+    # CacheBlend: register model with LMCache tracker before KV
+    # connector init, because LMCBlenderBuilder.get_or_create() calls
+    # VLLMModelTracker.get_model() during connector initialization.
+    try:
+        from lmcache.v1.compute.models.utils import VLLMModelTracker
+        VLLMModelTracker.register_model(
+            "vllm-instance", self.model_runner.model)
+    except ImportError:
+        pass
```
[the remark this answers is not in the document]
Comment (chjs) [reply examples/blend_kv_v1/README.md:29]: Fixed. Replaced with ENGINE_NAME constant.

File: lmcache/v1/compute/models/utils.py [hunk 2]
```diff
@@ -18,7 +18,10 @@ def infer_model_from_vllm(vllm_model, blender, enable_sparse: bool = False):
         from lmcache.v1.compute.models.llama import LMCLlamaModel
 
         return LMCLlamaModel(vllm_model, blender, enable_sparse)
-    elif model_name == "Qwen2ForCausalLM":
+    # Mistral shares a highly similar architecture with Llama and Qwen2
+    # (e.g., GQA and RoPE), allowing it to reuse the LMCLlamaModel
+    # implementation for LMCache-related tasks.
+    elif model_name in ("Qwen2ForCausalLM", "MistralForCausalLM"):
```
[the remark this answers is not in the document]
Comment (chjs) [reply lmcache/v1/compute/models/utils.py]: Fixed. Merged all three models into a single conditional block.

File: lmcache/v1/compute/models/base.py [hunk 3]
```diff
@@ -69,7 +71,8 @@ def compute_layer(
         input_ids: torch.Tensor,
     ):
         input_ids = input_ids.cuda()
-        hidden_states = self.vllm_model.get_input_embeddings(input_ids)
+        # vLLM V1 engines change the interface for accessing input embeddings.
+        hidden_states = self.vllm_model.model.embed_input_ids(input_ids)
```
[the remark this answers is not in the document]
Comment (chjs) [reply lmcache/v1/compute/models/base.py:73]: These are API compatibility fixes (import paths, method names) validated by passing CI (k3-correctness, k3-integration, unit-tests) and manual E2E testing documented in the PR description.

File: lmcache/v1/compute/models/base.py [hunk 4]
```diff
@@ -44,7 +44,9 @@ def __init__(
         rotary_emb = vllm_model.model.layers[0].self_attn.rotary_emb
         head_dim = rotary_emb.head_size
         max_position_embeddings = rotary_emb.max_position_embeddings
-        rope_scaling = None
+        # Use getattr to safely retrieve rope_scaling, as it may not be present
+        # in all vLLM configurations or versions.
+        rope_scaling = getattr(rotary_emb, "rope_scaling", None)
```
[the remark this answers is not in the document]
Comment (chjs) [reply lmcache/v1/compute/models/base.py]: Good catch. The original None hardcoding was intentional - CacheBlend does not support rope_scaling yet, and validate_rope_params rejects non_None values. Kept as-is.

File: lmcache/v1/compute/models/base.py [hunk 5]
```diff
@@ -44,6 +44,8 @@ def __init__(
         rotary_emb = vllm_model.model.layers[0].self_attn.rotary_emb
         head_dim = rotary_emb.head_size
         max_position_embeddings = rotary_emb.max_position_embeddings
+        # Use getattr to safely retrieve rope_scaling, as it may not be present
+        # in all vLLM configurations or versions.
```
[the remark this answers is not in the document]
Comment (chjs) [reply lmcache/v1/compute/models/base.py]: Fixed. Removed the stale comment - it was left over from a previous revision where `getattr` was used. The code now matches: `rope_scaling = None` with no misleading comment.
