### PR TITLE
[Bugfix] Compatible with CUDA 13.4.1

### PR DESCRIPTION
**Pull request by chunxiaozheng**
## Problem

K3 unit tests started failing with `cuda-bindings==13.4.1`:

```text
AttributeError: 'cuda.bindings.runtime.cudaIpcMemHandle_t' has no attribute 'reserved'
```

Starting with cuda-bindings 13.4, `cudaIpcMemHandle_t` is exposed as an opaque handle and no longer provides the `reserved` Python attribute.

LMCache previously serialized and reconstructed CUDA IPC handles by directly reading and writing this attribute.

## Origin

The direct `cudaIpcMemHandle_t.reserved` access in `RawCudaIPCWrapper` was introduced by PR #3829.

The same assumption was later used by the timeline-semaphore IPC backend introduced in PR #4551.

PR #4579 added the floating dependency:

```text
cuda-python>=13,<14
```

Therefore, CI began resolving `cuda-bindings==13.4.1` after its release, exposing the existing compatibility issue.

### CODE REVIEW

**Review by maobaolong — APPROVED** [review]
LGTM

**Review by royyhuang — APPROVED** [review]
LGTM
