### PR TITLE
fix: correct log and raise calls that drop their message at runtime (#4539)

### LINKED ISSUE #4539: [Bug] Logging calls pass more args than their format string consumes, so the message is dropped at runtime
### Describe the bug

Three `logger.*` calls in `lmcache/` pass more positional arguments than their format string consumes.

`logging` renders a record lazily as `msg % args`, so these calls raise `TypeError: not all arguments converted during string formatting` *inside* the logging machinery. Python's logging catches that and prints `--- Logging error ---` plus a traceback to stderr — **the intended message is never emitted**.

All three sit on failure paths, which is exactly where losing the message hurts most.

**1. `lmcache/v1/storage_backend/p2p_backend.py:155`** — two arguments, one placeholder. The caught exception `e` is silently dropped:

```python
except Exception as e:
    logger.error("Failed to close peer %s lookup socket", self.peer_init_url, e)
```

**2. `lmcache/v1/storage_backend/connector/mock_connector.py:266`** and **3. `mock_connector.py:278`** — a stray comma where implicit string concatenation was intended, so the message is truncated and its tail silently becomes an argument:

```python
logger.warning(
    f"Mock object is None on {i}",
    f" out of {len(mock_objs)} objects",
)
```

```python
logger.warning(
    "Failed to allocate memory even with",
    f" busy loop on {i} out of {len(mock_objs)} objects",
)
```

### To Reproduce

```python
import logging, sys

logging.basicConfig(level=logging.DEBUG, stream=sys.stdout)
log = logging.getLogger("repro")
log.error("Failed to close peer %s lookup socket", "tcp://1.2.3.4:80", ValueError("boom"))
```

Output — note the message and the exception are both lost:

```
--- Logging error ---
Traceback (most recent call last):
  ...
  File ".../logging/__init__.py", line 400, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Message: 'Failed to close peer %s lookup socket'
Arguments: ('tcp://1.2.3.4:80', ValueError('boom'))
```

### Why CI does not catch this today

Ruff's `PLE1205` / `PLE1206` (logging too-many / too-few args) are not in the `select` list in `pyproject.toml`, and `G` (flake8-logging-format) is commented out.

Enabling **only** `PLE1205` and `PLE1206` reports exactly the two static cases above and nothing else repo-wide, so the rules can be turned on with no additional cleanup:

```
$ ruff check --select PLE1205,PLE1206 .
lmcache/v1/storage_backend/connector/mock_connector.py:278:17: PLE1205 Too many arguments for `logging` format string
lmcache/v1/storage_backend/p2p_backend.py:155:13: PLE1205 Too many arguments for `logging` format string
Found 2 errors.
```

(For contrast, the full `G` ruleset currently reports 511 findings, mostly the f-string logging that is already being migrated incrementally — so `G` is deliberately out of scope here.)

Ruff cannot see through the f-string in case 2, so that variant needs a small test to stay covered while the f-string → `%`-format migration is in progress.

### Environment

- LMCache `dev` @ `0373a573`
- Bugs introduced in #1500 (Sep 2025) and #2148 (Dec 2025); both still present on `dev`.

I have a fix ready and will open a PR referencing this issue.

### PR DESCRIPTION
**Pull request by Anai-Guo**
## What this PR does / why we need it

Fixes #4539.

Three `logger.*` calls pass more positional arguments than their format string consumes. `logging` renders a record lazily as `msg % args`, so each raises `TypeError: not all arguments converted during string formatting` **inside** the logging machinery. Python's logging swallows that and prints a `--- Logging error ---` traceback to stderr instead — **the intended message is never emitted**. All three sit on failure paths, which is exactly where losing the message hurts most.

**1. `lmcache/v1/storage_backend/p2p_backend.py`** — one `%s` placeholder, two args. The caught exception `e` had no placeholder and was silently dropped:

```python
-logger.error("Failed to close peer %s lookup socket", self.peer_init_url, e)
+logger.error(
+    "Failed to close peer %s lookup socket: %s", self.peer_init_url, e
+)
```

**2 & 3. `lmcache/v1/storage_backend/connector/mock_connector.py`** — a stray comma where implicit string concatenation was intended. This truncated the message and turned its tail into an argument. Both rewritten as `%`-format.

## Preventing regressions

`PLE1205` / `PLE1206` (logging too-many / too-few args) were not in the ruff `select` list. Enabling **only** those two rules reports **exactly the two statically-visible cases and nothing else repo-wide**, so they turn on with no extra cleanup:

```
$ ruff check --select PLE1205,PLE1206 .
All checks passed!     # after this PR; 2 errors before it
```

Ruff cannot see through the f-string in the second `mock_connector.py` case, so a small regression test (`tests/v1/distributed/test_mock_connector_logging.py`) renders every emitted record and asserts the message survives — `record.getMessage()` raises `TypeError` before the fix.

`G` (flake8-logging-format) is deliberately left commented out; it reports hundreds of findings from the f-string logging still being migrated, and is out of scope here.

## Verification

- `ruff check --select PLE1205,PLE1206 .` → clean (pinned ruff 0.11.7).
- `ruff format --check` → clean.
- Extracted the real `_batched_get` (old vs new) and drove it against fakes: the old version's `getMessage()` raises `TypeError` (message dropped); the new version renders `Mock object is None on 0 out of 1 objects`.

---

## Update: two `raise` sites with the same defect

While confirming the ruff rules cover the file, two `ValueError` raises turned up with the
identical comma-instead-of-concatenation mistake. `PLE1205`/`PLE1206` only inspect logging
calls, so neither rule catches them:

`lmcache/v1/storage_backend/connector/mock_adapter.py`

```python
raise ValueError(
    f"Invalid capacity '{parsed.netloc}' for",
    " mock connector; must be an integer (GB).",
) from e
```

`lmcache/v1/storage_backend/connector/mock_connector.py` (`AsyncLRU.put`)

```python
raise ValueError(
    f"Allocation size {alloc_size} is",
    " greater than capacity {self.capacity}",
)
```

The comma makes each half a separate exception argument, so the rendered message is a tuple
repr; the second half of the `AsyncLRU.put` message is also missing its `f` prefix, so the
capacity is never interpolated:

```
before  ('Allocation size 5 is', ' greater than capacity {self.capacity}')
after   Allocation size 5 is greater than capacity 3
```

Both are fixed by dropping the comma (and adding the missing `f`), which is a pure message
change. `ruff check` and `ruff format --check` stay clean on both files with the pinned
0.11.7.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Anai-Guo** [comment]
Pushed one more commit: two `raise ValueError(...)` sites in the same connector pair carry the identical comma-instead-of-concatenation mistake, and `PLE1205`/`PLE1206` do not see them because those rules only inspect logging calls.

- `mock_adapter.py` — `f"Invalid capacity '{parsed.netloc}' for", " mock connector; must be an integer (GB)."`
- `mock_connector.py` (`AsyncLRU.put`) — `f"Allocation size {alloc_size} is", " greater than capacity {self.capacity}"`, whose second half is also missing its `f` prefix.

Rendered:

```
before  ('Allocation size 5 is', ' greater than capacity {self.capacity}')
after   Allocation size 5 is greater than capacity 3
```

Message-only change; `ruff check` / `ruff format --check` remain clean on both files with the pinned 0.11.7. Happy to split this into its own PR if you would rather keep this one to the logging call sites.
