### PR TITLE
fix(logging): pass the arguments these log calls actually render (#4539)

### LINKED ISSUE #4539: [Bug] Logging calls pass more args than their format string consumes, so the message is dropped at runtime
### Describe the bug

Three `logger.*` calls in `lmcache/` pass more positional arguments than their format string consumes.

`logging` renders a record lazily as `msg % args`, so these calls raise `TypeError: not all arguments converted during string formatting` *inside* the logging machinery. Python's logging catches that and prints `--- Logging error ---` plus a traceback to stderr — **the intended message is never emitted**.

All three sit on failure paths, which is exactly where losing the message hurts most.

**1. `lmcache/v1/storage_backend/p2p_backend.py:155`** — two arguments, one placeholder. The caught exception `e` is silently dropped:

```python
except Exception as e:
    logger.error("Failed to close peer %s lookup socket", self.peer_init_url, e)
```

**2. `lmcache/v1/storage_backend/connector/mock_connector.py:266`** and **3. `mock_connector.py:278`** — a stray comma where implicit string concatenation was intended, so the message is truncated and its tail silently becomes an argument:

```python
logger.warning(
    f"Mock object is None on {i}",
    f" out of {len(mock_objs)} objects",
)
```

```python
logger.warning(
    "Failed to allocate memory even with",
    f" busy loop on {i} out of {len(mock_objs)} objects",
)
```

### To Reproduce

```python
import logging, sys

logging.basicConfig(level=logging.DEBUG, stream=sys.stdout)
log = logging.getLogger("repro")
log.error("Failed to close peer %s lookup socket", "tcp://1.2.3.4:80", ValueError("boom"))
```

Output — note the message and the exception are both lost:

```
--- Logging error ---
Traceback (most recent call last):
  ...
  File ".../logging/__init__.py", line 400, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Message: 'Failed to close peer %s lookup socket'
Arguments: ('tcp://1.2.3.4:80', ValueError('boom'))
```

### Why CI does not catch this today

Ruff's `PLE1205` / `PLE1206` (logging too-many / too-few args) are not in the `select` list in `pyproject.toml`, and `G` (flake8-logging-format) is commented out.

Enabling **only** `PLE1205` and `PLE1206` reports exactly the two static cases above and nothing else repo-wide, so the rules can be turned on with no additional cleanup:

```
$ ruff check --select PLE1205,PLE1206 .
lmcache/v1/storage_backend/connector/mock_connector.py:278:17: PLE1205 Too many arguments for `logging` format string
lmcache/v1/storage_backend/p2p_backend.py:155:13: PLE1205 Too many arguments for `logging` format string
Found 2 errors.
```

(For contrast, the full `G` ruleset currently reports 511 findings, mostly the f-string logging that is already being migrated incrementally — so `G` is deliberately out of scope here.)

Ruff cannot see through the f-string in case 2, so that variant needs a small test to stay covered while the f-string → `%`-format migration is in progress.

### Environment

- LMCache `dev` @ `0373a573`
- Bugs introduced in #1500 (Sep 2025) and #2148 (Dec 2025); both still present on `dev`.

I have a fix ready and will open a PR referencing this issue.

### PR DESCRIPTION
**Pull request by Anai-Guo**
**What this PR does / why we need it**:

Fixes #4539

Three `logger.*` calls in `lmcache/` pass more positional arguments than their format string consumes. `logging` renders a record lazily as `msg % args`, so each of these raises `TypeError: not all arguments converted during string formatting` *inside* the logging machinery. Python's logging catches that and prints `--- Logging error ---` plus a traceback to stderr instead — **the intended message is never emitted**. All three sit on failure paths, which is exactly where losing the message hurts most.

**1. `lmcache/v1/storage_backend/p2p_backend.py:155`** — two arguments, one placeholder, so the caught exception was silently dropped:

```python
except Exception as e:
    logger.error("Failed to close peer %s lookup socket", self.peer_init_url, e)
```

The exception is now rendered by its own placeholder.

**2 & 3. `lmcache/v1/storage_backend/connector/mock_connector.py:266,278`** — a stray comma where implicit string concatenation was intended, so each message was truncated and its tail silently became an argument:

```python
logger.warning(
    f"Mock object is None on {i}",
    f" out of {len(mock_objs)} objects",
)
```

Both are rejoined into one message and converted to `%`-format, matching the deferred-formatting convention the repo is migrating to.

**Special notes for your reviewers**:

Two layers guard against a regression:

- **`PLE1205`/`PLE1206` added to `[tool.ruff.lint] select`.** These were not previously selected. With them enabled, `ruff check .` (v0.11.7, the `.pre-commit-config.yaml` pin) is clean repo-wide — the only two findings were the plain-string cases fixed here, so no additional cleanup rides along. The full `G` ruleset stays out of scope: it still reports ~500 findings from the f-string logging migration that is in progress.

- **`tests/test_logging_format.py`.** Ruff cannot count placeholders inside an f-string, so case 2 above is invisible to `PLE1205`. A small AST walk over `lmcache/` compares each logging call's placeholder count against its positional-argument count, which covers the f-string variant too. Two unit tests pin the guard itself (it flags the stray-comma shape, and leaves a well-formed call alone).

Verified against the tree at `e8f9381`:

| | `test_logging_arguments_match_format_string` |
|---|---|
| before the source fix | **FAILS** — reports all 3 call sites, including the 2 f-string ones ruff misses |
| after the source fix | **PASSES** |

`ruff check`, `ruff format --diff` and `isort --diff` are clean on all four files.

**If applicable**:

- [ ] this PR contains user facing changes - docs added
- [x] this PR contains unit tests

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Anai-Guo** [comment]
Closing as a duplicate — I filed #4587 for the same issue five minutes earlier, with the same three source fixes and the same `PLE1205`/`PLE1206` addition. Apologies for the noise; please review #4587 instead.

The only thing that differs here is the regression test. #4587 exercises the `mock_connector` call sites directly; this branch (`Anai-Guo:fix/logging-format-arg-count`) instead adds an AST guard that walks all of `lmcache/` and compares each logging call's placeholder count to its positional-argument count, so it also covers the f-string form that `PLE1205` cannot see anywhere in the tree, not just at these two call sites. Happy to move that over to #4587 if you'd prefer the broader guard.
